name: geom_eigen_model
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - networkx==3.4.2
      - lapy==1.1.1
      - seaborn==0.13.2
      - numpy==1.26.4
      - colormaps==0.4.2
      - scipy==1.13.1
      - brainspace==0.1.16
      - numba==0.60.0
      - pandas==2.2.3
      - nibabel==5.3.2
      - matplotlib==3.9.2
      - bctpy==0.6.1
